//About Component
function About(){
  return(
    <div className="about">
        <h1 style={{textAlign:"center"}}>About Us</h1>
        <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Iste reiciendis doloribus accusamus aperiam non nam nisi eum optio recusandae eveniet pariatur soluta, eaque veniam delectus id omnis necessitatibus. Cupiditate, ratione asperiores fugit repudiandae nesciunt consequatur at eveniet inventore vel non similique veniam deserunt culpa nam ipsa recusandae harum odio nemo ad voluptate animi officiis officia, assumenda nobis? Officia, maxime itaque asperiores laudantium reprehenderit aspernatur quaerat impedit, fugit omnis minus at placeat quod consectetur eum officiis exercitationem velit ex temporibus obcaecati cupiditate reiciendis culpa aliquid. Cumque, dolor! Dicta fugiat provident quibusdam neque veniam necessitatibus maiores. Laudantium minima nihil libero repellat esse non aperiam praesentium veniam omnis officia labore, quasi saepe consequatur sint quam! Dolorem praesentium odit sint, corporis sequi, ab fugiat veritatis quaerat quae nobis numquam excepturi blanditiis. Libero voluptatum dolorem natus maiores modi officia? Quidem dicta cupiditate reiciendis, commodi fugiat ab dolores impedit vel iste suscipit natus eaque magni delectus accusantium, quod nihil! Laborum magnam doloribus soluta repellendus est illum delectus accusantium voluptate eligendi quidem aut, vero nostrum commodi unde officiis exercitationem! Illum vero odio sed commodi deleniti dignissimos dolore eligendi? Vel, iste? Nemo quos nostrum expedita earum animi eius natus neque accusantium consequuntur? Consequatur beatae debitis qui. Neque a, fugit nesciunt distinctio adipisci fugiat ipsam commodi nostrum eius unde animi non dolorum enim aliquam nam id voluptatum sequi, exercitationem harum nulla iste error. Quam quidem cumque ipsa unde delectus aliquid impedit recusandae. Corrupti nemo recusandae facere nisi asperiores dolores deserunt maiores dolorum? Temporibus unde voluptatibus maxime officiis rerum natus veritatis veniam commodi ducimus, et necessitatibus sit tempora! Architecto unde tenetur iste, numquam voluptatum earum expedita id sit nam accusamus consequuntur mollitia officia. Optio commodi consequatur ab repellat eum assumenda esse quia temporibus dolores porro ratione vitae ad sint laboriosam necessitatibus, dignissimos dicta doloribus accusantium? Ipsum nihil itaque ea veritatis.</p>
    </div>
  )
}
export default About;